site_name: napari-plugin-accelerator
site_description: A demo for the plugin accelerator program presentation
site_author: Andy Sweet

theme: readthedocs


repo_url: https://github.com/andy-sweet/napari-plugin-accelerator

pages:
- Home: index.md
